### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/home/linux/.dedop/dedop.log

### ISSUE THREAD

**Issue by probonopd** [DeDop/dedop-studio#2]
### Expected behavior

AppImage can be launched on any recent Linux distribution

### Actual behavior

On openSUSE LEAP 42.2 I get:

```
linux@linux:~> /home/linux/Downloads/DeDop-studio-1.0.0-x86_64.AppImage 
6940
A JavaScript error occurred in the main process
Uncaught Exception:
Error: ENOENT: no such file or directory, open '/home/linux/.dedop/dedop.log'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1343:33)
    at Object.fs.appendFileSync (fs.js:1402:6)
    at writeToLogFile (/tmp/.mount_5r19Hh/usr/bin/resources/app.asar/main/main.js:181:8)
    at Object.init (/tmp/.mount_5r19Hh/usr/bin/resources/app.asar/main/main.js:184:5)
    at Object.<anonymous> (/tmp/.mount_5r19Hh/usr/bin/resources/app.asar/main.js:2:6)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
```

### Steps to reproduce the issue

1. Run openSUSE LEAP 42.2
2. Download DeDop-studio-1.0.0-x86_64.AppImage 
3. Make executable and try to run from the command line 

### Specifications 
openSUSE LEAP 42.2

**Comment by hans-permana** [comment]
Hi @probonopd,

Have you followed the installation steps as stated in here https://github.com/DeDop/dedop-installer? 

There are two components of dedop software, backend component (dedop-core) and frontend component (dedop-studio), with the frontend depending on the backend. At the moment, unfortunately the installation of two components have to be done separately, but we are planning to make them integrated in the future. 

PS. I have now added a link for installation through the installer in the readme

**Comment by probonopd** [comment]
Hi @hans-permana, no I just downloaded and executed the AppImage, as there is no "installation" expected to be necessary when using AppImages. Everyhting required to run should be integrated (bundled) in the AppImage.
